### ISSUE TITLE
temboard-agent ERROR:     raise ValueError('Not writable')

### ISSUE THREAD

**Issue by seadba** [dalibo/temboard-agent#145]
-bash-4.2$ temboard-agent -d -p /var/lib/temboard-agent/main/temboard-agent.pid
ERROR: Unhandled error:
ERROR: Traceback (most recent call last):
ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/cli.py", line 47, in cli_wrapper
ERROR:     retcode = main(argv, environ) or 1
ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/scripts/agent.py", line 103, in main
ERROR:     args=args, environ=environ,
ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/configuration.py", line 149, in load_configuration
ERROR:     config.load(args=args, environ=environ)
ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/configuration.py", line 264, in load
ERROR:     self.add_values(iter_defaults(self.specs))
ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/configuration.py", line 236, in add_values
ERROR:     value = spec.validate(value)
ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/configuration.py", line 127, in validate
ERROR:     return self.validator(value.value)
ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/validators.py", line 104, in writeabledir
ERROR:     raise ValueError('Not writable')
ERROR: ValueError: Not writable
ERROR: This is a bug!
ERROR: Please report traceback to https://github.com/dalibo/temboard-agent/issues! Thanks!

**Comment by bersace** [comment]
@seadba Thanks for the report ! Can you send me:

``` console
$ whoami
$ namei -om var/lib/temboard-agent/main/
```

**Comment by seadba** [comment]
thanks

[temboard@linux1 ~]$ whoami
temboard

[temboard@linux1 ~]$ namei -om /var/lib/temboard-agent/main/
f: /var/lib/temboard-agent/main/
 dr-xr-xr-x root     root     /
 drwxr-xr-x root     root     var
 drwxr-xr-x root     root     lib
 drwxr-xr-x postgres postgres temboard-agent
 drwxr-xr-x postgres postgres main

**Comment by bersace** [comment]
@seadba you should run temboard-agent as postgres user.

See http://temboard-agent.readthedocs.io/en/latest/temboard-agent-install-sources.html#operating-the-agent

**Comment by bersace** [comment]
@seadba the traceback has been fixed in master. If you still find something wrong, please reopen.
