### ISSUE TITLE
Asking for reload configuration with big min_wal_size and max _wal_size

### ISSUE THREAD

**Issue by PauloLaScience** [dalibo/temboard-agent#238]
You see a warning about reload configuration when min_wal_size=4GB and max _wal_size=8GB. You click to reload configuration and warning message stay. I didn't chage those values I just install temboard-agent.

**Comment by pgiraud** [comment]
Hi @PauloLaScience 
Can you give more information about where you saw the warning message?
If it's in your browser, a screenshot may help.

**Comment by PauloLaScience** [comment]
Hi,
Find attached a screenshot of the message
Kind regards,
Paul-Emmanuel

**Comment by pgiraud** [comment]
@PauloLaScience you replied by email which makes it impossible to see the image you attached.

**Comment by PauloLaScience** [comment]
![screenshot from 2018-08-06 14-06-18](https://user-images.githubusercontent.com/22047207/43887515-602dc8aa-9bbf-11e8-9cfe-203b3e9185d3.png)
It's on top when you click on the view of an instance. Maybe it's for temboard but I think Warning is push back by the temboard-agent.

**Comment by pgiraud** [comment]
@PauloLaScience I think I've been able to reproduce the issue. Can you confirm that you are running a version of Postgres greater than 10?

**Comment by PauloLaScience** [comment]
@pgiraud  As you can see it's a 10.4 but packaged by Citus Data with citus extension included.
![screenshot from 2018-08-10 07-44-56](https://user-images.githubusercontent.com/22047207/43940940-54d0b158-9c72-11e8-831d-7b530edfc303.png)

**Comment by PauloLaScience** [comment]
@pgiraud  As you can see it's a 10.4 but packaged by Citus Data with citus extension included.
![screenshot from 2018-08-10 07-44-56](https://user-images.githubusercontent.com/22047207/43940940-54d0b158-9c72-11e8-831d-7b530edfc303.png)

**Comment by pgiraud** [comment]
@PauloLaScience Is it possible for you to install a new version of the agent in order to confirm that we fixed the issue?
