### ISSUE TITLE
In V2.2 : auto-configure.sh script in case of the supervised postgres cluster is not in default port (PGPORT <> 5432 ) 

### ISSUE THREAD

**Issue by paupi25** [dalibo/temboard-agent#308]
Hy,

  in case of the Postgres cluster port (PGPORT) is not the default value,  the auto-configure.sh script must be change in line 38 and  in line 116 when the script connect into  the supervised Postgres cluster to get informations. 

In detail : 
 - please change line 38 `val=$(sudo -u ${PGUSER} psql -Atc "SELECT setting FROM pg_settings WHERE name = '${name}';")` by `val=$(sudo -u ${PGUSER} psql -p$PGPORT -Atc "SELECT setting FROM pg_settings WHERE name = '${name}';")`
 - please change line 116  `if ! sudo -Eu ${PGUSER} psql -tc "SELECT 'Postgres connection working.';" ; then` by `if ! sudo -Eu ${PGUSER} psql -p$PGPORT -tc "SELECT 'Postgres connection working.';" ; then`

In this 2 cases we must and the PGPORT at the psql command to connect to the target cluster and to have information on this cluster to have a good configuration generate by the auto-configure.sh script.

I have successfuly tested it. 

Regards

**Comment by bersace** [comment]
Thanks @paupi25 ! Do you feel able to propose a PR ?

**Comment by paupi25** [comment]
Hello,

  I never did it again ; I take a look to do it. I'm about to read the doc https://github.com/dalibo/temboard/blob/master/CONTRIBUTING.md 

David Paupe (paupi25) 

----- Mail d'origine -----
De: Étienne BERSAC <notifications@github.com>
À: dalibo/temboard-agent <temboard-agent@noreply.github.com>
Cc: paupi25 <david.paupe@free.fr>, Mention <mention@noreply.github.com>
Envoyé: Fri, 11 Jan 2019 10:40:17 +0100 (CET)
Objet: Re: [dalibo/temboard-agent] In V2.2 : auto-configure.sh script in case of the supervised postgres cluster is not in default port (PGPORT <> 5432 ) (#308)

Thanks @paupi25 ! Do you feel able to propose a PR ?—

**Comment by bersace** [comment]
@paupi25 ok, welcome to the world of contribution :-) You may find some info on using GitHub to propose a patch through : https://help.github.com/articles/creating-a-pull-request-from-a-fork/ .

Basically:

- Create your own fork on GitHub
- Clone it in your disk
- Create a new branch
- Edit auto_configure.sh, commit and push it to your clone (paupi25/temboard-agent)
- Open a Pull request to ask to merge your branch in dalibo/temboard-agent master.

I'll take care of backporting this and releasing packages. Dont' hesitate to ask for help. What package format do you use ?

**Comment by bersace** [comment]
@paupi25 oh yes, the fix is not release on PyPI but on RPM/DEB. We may consider releasing a `.post1` release on PyPI. @julmon ?

**Comment by paupi25** [comment]
Thanks for the answer I hope it will be fix in PyPi.

Regards

----- Mail d'origine -----
De: Étienne BERSAC <notifications@github.com>
À: dalibo/temboard-agent <temboard-agent@noreply.github.com>
Cc: paupi25 <david.paupe@free.fr>, Mention <mention@noreply.github.com>
Envoyé: Thu, 17 Jan 2019 16:44:33 +0100 (CET)
Objet: Re: [dalibo/temboard-agent] In V2.2 : auto-configure.sh script in case of the supervised postgres cluster is not in default port (PGPORT <> 5432 ) (#308)

@paupi25 oh yes, the fix is not release on PyPI but on RPM/DEB. We may consider releasing a .post1 release on PyPI. @julmon ?—

**Comment by bersace** [comment]
@paupi25 I uploaded agent 2.3.1 on PyPI and Dalibo labs repositories. Can you test this ?

**Comment by bersace** [comment]
Hi @paupi25,

Upgrade like a regular Python egg : `pip install --upgrade temboard-agent`.

**Comment by paupi25** [comment]
Ok,
 
  I try by upgrading temboard-agent and by reinstalling with PyPi tool, and by the 2 way all works well.

Version Temboard-agent 2.3.1
Command to configigure temboard-agent on database in port 5433 : 
  - export PGPORT=5433 ; /usr/local/share/temboard-agent/auto_configure.sh  https://srvdco03.dco.fra:8899

Well done and good job.

Thks

Regards

David Paupe
  
----- Mail d'origine -----
De: Étienne BERSAC <notifications@github.com>
À: dalibo/temboard-agent <temboard-agent@noreply.github.com>
Cc: paupi25 <david.paupe@free.fr>, Mention <mention@noreply.github.com>
Envoyé: Mon, 21 Jan 2019 09:39:48 +0100 (CET)
Objet: Re: [dalibo/temboard-agent] In V2.2 : auto-configure.sh script in case of the supervised postgres cluster is not in default port (PGPORT <> 5432 ) (#308)

Hi @paupi25,Upgrade like a regular Python egg : pip install --upgrade temboard-agent.—
