### ISSUE TITLE
Problem Registering Agent

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard-agent#320]
Running v2.2.

I tried to register an agent and it seemed to go Ok but in the dashboard I don't see any data, although if I click the View button for the agent I connect and everything looks fine. I can see "connection refused" errors in the temboard-agent.log file (attached).

Any idea what I've done wrong and how to correct it?

**Comment by bersace** [comment]
Hi @dgiffin . It seems you missed the log file attachement. Regards.

**Comment by dgiffin** [comment]
Arrggh  sorry!

**Comment by dgiffin** [comment]
[temboard-agent.log.gz](https://github.com/dalibo/temboard-agent/files/2915563/temboard-agent.log.gz)

**Comment by bersace** [comment]
No worry :-) The collector_url seems misconfigured. This is where the monitoring task sends monitoring data.

So i confirm the error in the log is related to the empty dashboard.

**Comment by dgiffin** [comment]
Thanks! I'll double check that setting and get back to you if it doesn't fix it.

**Comment by dgiffin** [comment]
Yes, my bad, problem fixed! We have two temboard server installations, one in the US and one in the EU, guess who hadn't set the config file to the correct server?

Thanks so much for the help, it's really appreciated.

**Comment by bersace** [comment]
You're welcome :-)
