### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by doronyaary** [dalibo/temboard-agent#327]
I have installed temboard-agent using pip installer. Then I started the service by using systemctl (on CentOS 7). The systemctl command returned no error but no open ports were found. I have already enabled port 2345 (by using firewall-cmd). I then ran systemctl status and found the following lines:

Mar 25 05:13:04 li1496-168.members.linode.com env[23009]: {'function': 'scheduled_reindex', 'splitpath': ['maintenance', 'reindex', 'scheduled'], 'module': 'temboardagent.plugins.maintenance', 'check_session': True, 'ht...eck_key': True}
Mar 25 05:13:04 li1496-168.members.linode.com env[23009]: Starting main process.
Mar 25 05:13:04 li1496-168.members.linode.com env[23009]: Starting worker pool.
Mar 25 05:13:04 li1496-168.members.linode.com env[23009]: Starting scheduler.
Mar 25 05:13:04 li1496-168.members.linode.com env[23009]: worker pool terminated.
Mar 25 05:13:04 li1496-168.members.linode.com env[23009]: scheduler terminated.
Mar 25 05:13:04 li1496-168.members.linode.com env[23009]: Failed to start HTTPS server: [Errno 13] Permission denied.
Mar 25 05:13:04 li1496-168.members.linode.com systemd[1]: temboard-agent@11-data.service: main process exited, code=exited, status=1/FAILURE
Mar 25 05:13:04 li1496-168.members.linode.com systemd[1]: Unit temboard-agent@11-data.service entered failed state.
Mar 25 05:13:04 li1496-168.members.linode.com systemd[1]: temboard-agent@11-data.service failed.

As far as I understand the service is running with the user "postgres". How can I resolve the "permission denied" issue? What else can I check?

Thanks!

**Comment by julmon** [comment]
Hello,

This error means temboard agent can not listen on the TCP port. Could you check if SELinux is enabled and if there is restrictions on ports ?

Regards,

**Comment by doronyaary** [comment]
Hello.

I have disabled SELinux. Yet, the same error happens. I have even tried to use higher port (e.g. 22345) but that doesn't work as well.

BTW: The server installation runs smoothly without any errors... hope this helps :-)

Thanks!

**Comment by julmon** [comment]
Could you try this command:
```console
$ sudo -u postgres python2 -m SimpleHTTPServer 2345
```

**Comment by bersace** [comment]
Closing stale issue. @doronyaary please reopen if you have updates !
