### ISSUE TITLE
Error starting agent services

### ISSUE THREAD

**Issue by GreenBeanKILLER** [dalibo/temboard-agent#328]
INFO: setuptools is too old for plugin hotload.
 INFO: If new plugin can't be found, just restart.
 INFO: Found plugin monitoring = temboardagent.plugins.monitoring:MonitoringPlugin.
 INFO: Found plugin dashboard = temboardagent.plugins.dashboard:DashboardPlugin.
 INFO: Found plugin pgconf = temboardagent.plugins.pgconf:PgConfPlugin.
 INFO: Found plugin administration = temboardagent.plugins.administration:AdministrationPlugin.
 INFO: Found plugin activity = temboardagent.plugins.activity:ActivityPlugin.
 INFO: Found plugin maintenance = temboardagent.plugins.maintenance:MaintenancePlugin.
 INFO: Loading plugin monitoring.
ERROR: Unhandled error:
ERROR: Traceback (most recent call last):
ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/toolkit/app.py", line 256, in entrypoint
ERROR:     retcode = self.main(argv, environ)
ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/scripts/agent.py", line 96, in main
ERROR:     self.bootstrap(args=args, environ=environ)
ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/toolkit/app.py", line 99, in bootstrap
ERROR:     self.apply_config()
ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/cli.py", line 50, in apply_config
ERROR:     return super(Application, self).apply_config()
ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/toolkit/app.py", line 151, in apply_config
ERROR:     self.update_plugins(old_plugins=old_plugins)
ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/toolkit/app.py", line 218, in update_plugins
ERROR:     self.plugins[name].load()
ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/plugins/monitoring/__init__.py", line 293, in load
ERROR:     pg_version = self.app.postgres.fetch_version()
ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/postgres.py", line 54, in fetch_version
ERROR:     with self.connect() as conn:
ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/postgres.py", line 23, in __enter__
ERROR:     self.conn.connect()
ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/spc.py", line 827, in connect
ERROR:     self._password.encode() +
ERROR: AttributeError: 'NoneType' object has no attribute 'encode'
ERROR: temboardagent version is 3.0.
ERROR: This is a bug!
ERROR: Please report traceback to https://github.com/dalibo/temboard-agent! Thanks!

**Comment by GreenBeanKILLER** [comment]
[temboard]
# Bind port.
port = 2345
# Bind address.
address = 0.0.0.0
# User & password file.
users = users
# Plugins in use.
plugins = ["monitoring", "dashboard", "pgconf", "administration", "activity", "maintenance"]
# SSL: certificat file path (.pem)
#ssl_cert_file = temboard-agent_CHANGEME.pem
ssl_cert_file = ssl/localhost.pem
# SSL: private key file path (.key)
#ssl_key_file = temboard-agent_CHANGEME.key
ssl_key_file = ssl/localhost.key
# Hostname must be an unique and valid FQDN : e.g. db1.mydomain.foo
# If you leave this empty, then the system wide hostname will be used
# Note : `localhost` is not a correct value
hostname = XXXXXXXXX
# Key
key = SECRETKEYTOBECHANGED

[postgresql]
# Unix socket path.
host = /var/run/postgresql
# PG port number.
port = 5432
# Super-user name.
user = postgres
# Super-user password.
# password =
# Default database.
dbname = postgres
# Instance name.
instance = main

[logging]
# Available methods for logging: stderr, syslog or file
method = stderr
# Syslog facility.
# facility = local0
# Log destination, should be /dev/log for syslog on Linux system.
# When using file logging method, this is referencing the log file path.
# destination = /var/log/temboard-agent/temboard-agent.log
# Log level, can be: DEBUG, INFO, WARNING, ERROR or CRITICAL.
level = INFO

### PLUGINS ###
[dashboard]
# Dashboard plugin part
# Interval, in second, between each run of the process collecting
# data used to render the dashboard. Default: 2
# scheduler_interval = 2
# Number of record to keep. Default: 150
# history_length = 150

[monitoring]
# Monitoring plugin part.
# DB name list (comma separator) to supervise. * for all.
dbnames = *
# Collector URL. (defaults to TEMBOARD_MONITORING_COLLECTOR_URL env var)
# collector_url = https://0.0.0.0:8888/monitoring/collector
# List of probes to run, comma separator, * for all.
# Available probes: locks,process,db_size,tblspc_size,sessions,blocks,xacts,replication,loadavg,filesystems_size,cpu,bgwriter,memory,wal_files
# when monitoring a standby server, 'wal_file' probe shouldn't be loaded.
probes = *
# Interval, in second, between each run of the process executing
# the probes. Default: 60
# scheduler_interval = 60
# File where to store collector's SSL certificate.
# ssl_ca_cert_file = temboard-agent_ca_certs_CHANGEME.pem

[administration]
# External command used for start/stop PostgreSQL.
# This commands actually works on Debian jessie.
pg_ctl = '/usr/lib/postgresql/9.4/bin/pg_ctl %s -D /var/lib/postgresql/9.4'

**Comment by GreenBeanKILLER** [comment]
[temboard]
# Bind port.
port = 2345
# Bind address.
address = 0.0.0.0
# User & password file.
users = users
# Plugins in use.
plugins = ["monitoring", "dashboard", "pgconf", "administration", "activity", "maintenance"]
# SSL: certificat file path (.pem)
#ssl_cert_file = temboard-agent_CHANGEME.pem
ssl_cert_file = ssl/localhost.pem
# SSL: private key file path (.key)
#ssl_key_file = temboard-agent_CHANGEME.key
ssl_key_file = ssl/localhost.key
# Hostname must be an unique and valid FQDN : e.g. db1.mydomain.foo
# If you leave this empty, then the system wide hostname will be used
# Note : `localhost` is not a correct value
hostname = NOCSrvPostgresLAB02
# Key
key = SECRETKEYTOBECHANGED

[postgresql]
# Unix socket path.
host = /var/run/postgresql
# PG port number.
port = 5432
# Super-user name.
user = postgres
# Super-user password.
# password =
# Default database.
dbname = postgres
# Instance name.
instance = main

[logging]
# Available methods for logging: stderr, syslog or file
method = stderr
# Syslog facility.
# facility = local0
# Log destination, should be /dev/log for syslog on Linux system.
# When using file logging method, this is referencing the log file path.
# destination = /var/log/temboard-agent/temboard-agent.log
# Log level, can be: DEBUG, INFO, WARNING, ERROR or CRITICAL.
level = INFO

### PLUGINS ###
[dashboard]
# Dashboard plugin part
# Interval, in second, between each run of the process collecting
# data used to render the dashboard. Default: 2
# scheduler_interval = 2
# Number of record to keep. Default: 150
# history_length = 150

[monitoring]
# Monitoring plugin part.
# DB name list (comma separator) to supervise. * for all.
dbnames = *
# Collector URL. (defaults to TEMBOARD_MONITORING_COLLECTOR_URL env var)
# collector_url = https://0.0.0.0:8888/monitoring/collector
# List of probes to run, comma separator, * for all.
# Available probes: locks,process,db_size,tblspc_size,sessions,blocks,xacts,replication,loadavg,filesystems_size,cpu,bgwriter,memory,wal_files
# when monitoring a standby server, 'wal_file' probe shouldn't be loaded.
probes = *
# Interval, in second, between each run of the process executing
# the probes. Default: 60
# scheduler_interval = 60
# File where to store collector's SSL certificate.
# ssl_ca_cert_file = temboard-agent_ca_certs_CHANGEME.pem

[administration]
# External command used for start/stop PostgreSQL.
# This commands actually works on Debian jessie.
pg_ctl = '/usr/lib/postgresql/9.4/bin/pg_ctl %s -D /var/lib/postgresql/9.4'

**Comment by julmon** [comment]
Hi,

You should configure `postgres` password in the conf. file.

**Comment by GreenBeanKILLER** [comment]
abr 01 14:54:40 NOCSrvPostgresLAB02 polkitd[801]: Unregistered Authentication Agent for unix-process:16163:345852891 (system bus name :1.13576, object path /org/freedes
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]: setuptools is too old for plugin hotload.
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]: If new plugin can't be found, just restart.
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]: Found plugin monitoring = temboardagent.plugins.monitoring:MonitoringPlugin.
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]: Found plugin dashboard = temboardagent.plugins.dashboard:DashboardPlugin.
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]: Found plugin pgconf = temboardagent.plugins.pgconf:PgConfPlugin.
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]: Found plugin administration = temboardagent.plugins.administration:AdministrationPlugin.
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]: Found plugin activity = temboardagent.plugins.activity:ActivityPlugin.
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]: Found plugin maintenance = temboardagent.plugins.maintenance:MaintenancePlugin.
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]: Loading plugin monitoring.
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]: Unhandled error:
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]: Traceback (most recent call last):
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]:   File "/usr/lib/python2.7/site-packages/temboardagent/toolkit/app.py", line 256, in entrypoint
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]:     retcode = self.main(argv, environ)
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]:   File "/usr/lib/python2.7/site-packages/temboardagent/scripts/agent.py", line 96, in main
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]:     self.bootstrap(args=args, environ=environ)
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]:   File "/usr/lib/python2.7/site-packages/temboardagent/toolkit/app.py", line 99, in bootstrap
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]:     self.apply_config()
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]:   File "/usr/lib/python2.7/site-packages/temboardagent/cli.py", line 50, in apply_config
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]:     return super(Application, self).apply_config()
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]:   File "/usr/lib/python2.7/site-packages/temboardagent/toolkit/app.py", line 151, in apply_config
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]:     self.update_plugins(old_plugins=old_plugins)
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]:   File "/usr/lib/python2.7/site-packages/temboardagent/toolkit/app.py", line 218, in update_plugins
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]:     self.plugins[name].load()
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]:   File "/usr/lib/python2.7/site-packages/temboardagent/plugins/monitoring/__init__.py", line 293, in load
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]:     pg_version = self.app.postgres.fetch_version()
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]:   File "/usr/lib/python2.7/site-packages/temboardagent/postgres.py", line 54, in fetch_version
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]:     with self.connect() as conn:
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]:   File "/usr/lib/python2.7/site-packages/temboardagent/postgres.py", line 23, in __enter__
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]:     self.conn.connect()
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]:   File "/usr/lib/python2.7/site-packages/temboardagent/spc.py", line 827, in connect
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]:     self._password.encode() +
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]: AttributeError: 'NoneType' object has no attribute 'encode'
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]: temboardagent version is 3.0.
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]: This is a bug!
abr 01 14:54:41 NOCSrvPostgresLAB02 env[16168]: Please report traceback to https://github.com/dalibo/temboard-agent! Thanks!
abr 01 14:54:41 NOCSrvPostgresLAB02 systemd[1]: temboard-agent@my_cluster.service: main process exited, code=exited, status=1/FAILURE
abr 01 14:54:41 NOCSrvPostgresLAB02 systemd[1]: Unit temboard-agent@my_cluster.service entered failed state.
abr 01 14:54:41 NOCSrvPostgresLAB02 systemd[1]: temboard-agent@my_cluster.service failed.

**Comment by julmon** [comment]
Hm, you shouldn't get this error with `postgres` password set in `temboard-agent.conf` file.
Could you please paste file new content here ?

Thanks,
