### ISSUE TITLE
logrotate?

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard-agent#340]
I can see my temboard-agent.log files are getting rotated but I can't see how as we do NOT have a file in /etc/logrotate.d for it, is this done some other way?

**Comment by bersace** [comment]
Hi @dgiffin , following installation instruction, you should have a logrotate file according to https://github.com/dalibo/temboard-agent/blob/master/share/auto_configure.sh#L219-L222 . How did you install agent ?

**Comment by dgiffin** [comment]
Found it, we had an old log tidy script that took care of this that has been deprecated internally, I'll put the logrotate.d file in place - thanks!

**Comment by bersace** [comment]
You're welcome, David !
