### ISSUE TITLE
Api call

### ISSUE THREAD

**Issue by pmpetit** [dalibo/temboard-agent#347]
Hello, 
modifying then agent is too complicated for me. I need too much reverse engineering to understand how it is running.
So i think i will not be able to split the agent from the host.

Is there a way to insert metrics in the repository using api ?
thanks

**Comment by bersace** [comment]
Hi @pmpetit . Yes. See `send_output` at https://github.com/dalibo/temboard-agent/blob/master/temboardagent/plugins/monitoring/output.py#L21 and a usage at https://github.com/dalibo/temboard-agent/blob/master/temboardagent/plugins/monitoring/__init__.py#L211

There is no documented API for this.

**Comment by bersace** [comment]
Closing stale issue. Please reopen if you have updates.
