### ISSUE TITLE
V4 agent documentation?

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard-agent#348]
I might have missed it, but I can't find the document for the v4 temboard-agent, especially the upgrade process. also, can we (temporarily) run v3 temboard-agents against a v4 temboard (server)?

**Comment by julmon** [comment]
Hello @dgiffin 

You're right, we forgot to add upgrade process in the documentation.
You just have to install the new temboard-agent package and restart the agent.

v3 agent is not fully compatible with v4 temboard server, some new features in maintenance plugin won't work.

**Comment by bersace** [comment]
Fixed. Closing.
