### ISSUE TITLE
setting up temboard-agent with multiple clusters on same host

### ISSUE THREAD

**Issue by bsislow** [dalibo/temboard-agent#351]
we have two clusters on one host, each being a different version and each having a different port.

cluster 1 - version 9.6.14
cluster 2 - version 11.4

we were able to start the temboard-agent on cluster 1, and we differentiate the agent for cluster 2 using different configuration file variables such as "home" and "host" but with systemctl we get (i removed the port number below and instead put PORTNUM):

```
temboard-agent[2353]: INFO: Found plugin dashboard = temboardagent.plugins.dashboard:DashboardPlugin.
temboard-agent[2353]: INFO: Found plugin pgconf = temboardagent.plugins.pgconf:PgConfPlugin.
temboard-agent[2353]: INFO: Found plugin administration = temboardagent.plugins.administration:AdministrationPlugin.
temboard-agent[2353]: INFO: Found plugin activity = temboardagent.plugins.activity:ActivityPlugin.
temboard-agent[2353]: INFO: Loading plugin administration.
temboard-agent[2353]: CRITI: Failed to connect to Postgres: Could not connect to /run/postgresql-PORTNUM <---------------
systemd[1]: temboard-agent-PORTNUM.service: control process exited, code=exited status=1
systemd[1]: Failed to start temBoard agent for PostgreSQL.
systemd[1]: Unit temboard-agent-PORTNUM.service entered failed state.
systemd[1]: temboard-agent-PORTNUM.service failed.
```

how do we properly distinguish multiple agents on the same host?

**Comment by bersace** [comment]
Hi @bsislow , thanks for the report;

Did you use `auto_configure.sh` to creates the two configurations ? See. https://temboard.readthedocs.io/projects/agent/en/v4/installation.html

**Comment by bsislow** [comment]
ah, we did not use that. i just tried it and i cannot get past the last step...

```
Getting system & PostgreSQL informations from the agent (https://xxx.xxx:PORTNUM/discover) ...
CRITI: <urlopen error EOF occurred in violation of protocol (_ssl.c:618)>
```

can you help here? sorry this is unrelated to the issue.

**Comment by bersace** [comment]
Hi @bsislow ,

The logs states that the agent can't communicate with PostgreSQL :

```
temboard-agent[2353]: CRITI: Failed to connect to Postgres: Could not connect to /run/postgresql-PORTNUM <---------------
```

Do you have a running PostgreSQL instance with socket in /run/postgresql-PORTNUM ?

`auto_configure.sh` connects to PostgreSQL using the same environment variables as `psql`. Thus it ensure Postgres connectivity at the moment of writing configuration. It's safer.

**Comment by bsislow** [comment]
we successfully configured 2 agents on the same host with auto_configure. thanks!

**Comment by bersace** [comment]
@bsislow thanks for the report ! Bravo ! :-)
