### ISSUE TITLE
temboard-agent-register: should read the port in auto.conf or temboard-agent.conf

### ISSUE THREAD

**Issue by Krysztophe** [dalibo/temboard-agent#357]
(I know, 'temboard-agent-register --port 2345' is clearly in the doc.)

After a succesfull  autoconfigure, I've set the port to 65113 in auto.conf and 666 in temboard-agent.conf, but deliberately forgot to set it on the command line with '--port': it goes back to the default on 2345 and fails. 
```
root@..:/etc/temboard-agent# rgrep port 11/pagode/temboard-agent.conf.d/auto.conf:port = 65113
11/pagode/temboard-agent.conf.d/auto.conf:port = 11003
11/pagode/temboard-agent.conf:# Bind port.
11/pagode/temboard-agent.conf:# port ignored
11/pagode/temboard-agent.conf:port = 666
11/pagode/temboard-agent.conf:# PG port number.
11/pagode/temboard-agent.conf:port = 5432

root@pegase:/etc/temboard-agent# sudo -u postgres temboard-agent-register -c /etc/temboard-agent/11/pagode/temboard-agent.conf  --host pegase.dalibo.net   --groups default https://localhost:3001
Getting system & PostgreSQL informations from the agent (https://pegase.dalibo.net:2345/discover) ...
2019-09-27 08:07:24,815 [27940] [app             ] CRITI: <urlopen error [Errno 111] Connection refused>
```
That's a shame that `temboard-agent-register` does not read the conf files, but I can live with this.
Of course, with  `--port=65113` on the command line, it registers successfully.

But there is worse : 

if there is already a working temboard-agent on 2345 for another instance, you may register this former temboard-agent a second time successfully (`agent_port` is the one from the file, so no PK error). So a new instance appears in Temboard with the correct name and the correct agent port, but pointing to the agent on 2345. Confusion ensues.
The following was obtained by launching `temboard-agent-register` for agent on port 65096 (a 9.6 instance) without `--port`. The v11 instance called piggy is registered twice with its own agent.
![Screenshot_20190927_175347](https://user-images.githubusercontent.com/22391138/65783324-dbee3c00-e14f-11e9-8ab4-7f7dc83399e3.png)

Summary : if temboard-agent-register cannot read the conf from the beginning,  `--port` should be compulsory on the command line.

**Comment by bersace** [comment]
Fixed in f154f9c70c2a4c26c087df29b4ebcd8ce218d134
