### ISSUE TITLE
Enhancement Request - Filtering Targets for Status Checks

### ISSUE THREAD

**Issue by bsislow** [dalibo/temboard-agent#366]
It would be very helpful to be able to pick and choose what targets are monitored by each Status check.

For example - for "File systems usage," we would like to ignore specific filesystem that we do not care about. This filesystem is critical but it's very large and it makes the check on the dashboard appear to be critical as well.

Another example - we would like to ignore the template0-1 databases as they don't have any meaning in a production context. We would like to ignore these, but include monitoring for the postgres and production database on each host.

Thanks.

**Comment by bersace** [comment]
Hi @bsislow . #540 should help by skipping remote file systems and mount points in /dev, /run, /sys and /proc. What do you think of this ?

**Comment by bsislow** [comment]
This should work for now. Preferably, we could choose the filesystems we want to monitor for each target. That would be ideal. 

Thanks again.
