### ISSUE TITLE
No more pg_class.relhasoids in postgresql 12 

### ISSUE THREAD

**Issue by madtibo** [dalibo/temboard-agent#371]
Hello,

I was testing temboard on version 12. There is a problem with 2 queries in [temboardagent/plugins/monitoring/probes.py.](https://github.com/dalibo/temboard-agent/blob/c63b82e243c9155e1878ba94e747b51761d62138/temboardagent/plugins/monitoring/probes.py#L865) and in [temboardagent/plugins/maintenance/functions.py](https://github.com/dalibo/temboard-agent/blob/c63b82e243c9155e1878ba94e747b51761d62138/temboardagent/plugins/maintenance/functions.py#L15) since there is no more relhasoids column in PostgreSQL 12.

Cordilalement,

**Comment by bersace** [comment]
Should be fixed. Closing.
