### ISSUE TITLE
Configurability

### ISSUE THREAD

**Issue by bersace** [dalibo/temboard-agent#44]
Let's move how temBoard agent is configured to the next step :-)

Some hint on what would be great:

- *override* settings from env var (alwost automatically: `TEMBOARD_<SECTION>_<ITEM>`).
- Relocatable configuration (allow to copy sample conf to /etc and run it as is).
- Pluggability: ease plugin configuration (do not reload configuration for each plugin).
- Composability: support `conf.d/` (relocatable too).
- Read users from env var ? e.g. `USERS_INLINE=alice:alice temboard-agent`
- Automatically create directories and files (home, users) ?
- Allow me to tell whether we are in secured infrastructure (check CA) or not (let's use self-signed cert or even plain HTTP).
- Warn on security issue. Allow to refuse to start with security warning.
  - SSL certificate invalid, untrusted, expired, etc.
  - `users` file readable by world.
- Testable and tested configuration marshalling
- Document settings mechanism : files, directories, priority (command line opt, file, env var, etc.)
- Document each settings (hepl2man ? help2rst ? man2rst ?)

### User stories

- As ops, I test temBoard agent on an existing cluster without configuration.
  That's ok if it's not secured. Just **warn me**.
- As ops, I deploy temBoard agent targeting a cluster for production.
  This installation must ensure security and conformance.
- As ops, I deploy several temBoard agent targeting each cluster for production.
  I can interact with each agent independently.
- As ops, I list available instance of temBoard agent and associated PG cluster

### Tasks

- [x] New configuration loading
- [x] Configuration reload
- [x] configdir
- [x] Migrated plugins
- [ ] Add --unsecure option

**Comment by julmon** [comment]
Thank you! I agree with most of this.

About env. var. usage, this is a cool idea. Just a detail, in your example about users, I would prefer to give the password hash instead of clear password.

**Comment by bersace** [comment]
Note that env vars can be secured depending on target system :

- https://www.freedesktop.org/software/systemd/man/systemd.exec.html#EnvironmentFile=
- https://docs.docker.com/compose/env-file/

See also how travis and circle CI manage secret env vars.

Anyway, never storing clear password is a good idea. We should do this also in the `Dockerfile`.

**Comment by bersace** [comment]
Unsetting CA cert file is equivalent to `--unsecure`. Let's close.
