### ISSUE TITLE
No module named temboardagent.sharedmemory

### ISSUE THREAD

**Issue by aanriot** [dalibo/temboard-agent#47]
@julmon, @bersace ,

I just tried to restart a temboard agent which has been installed a few weeks ago on a server, and got the following error:

```
mai 12 10:33:44 server temboard-agent[30486]: File "/usr/bin/temboard-agent", line 6, in <module>
mai 12 10:33:44 server temboard-agent[30486]: from temboardagent.sharedmemory import Commands, Sessions
mai 12 10:33:44 server temboard-agent[30486]: ImportError: No module named temboardagent.sharedmemory
```

Though, it was working previously, and the lib appears to be already there:

```
-rw-r--r-- 1 root root 9,5K mai    4 11:00 /usr/lib/python2.7/site-packages/temboardagent/sharedmemory.py
```

Both server and agent were installed through Debian packages (jessie/amd64), here is what APT says:

```
# apt-cache policy temboard-agent
temboard-agent:
  Installé : 1.0~a1-0dlb1
  Candidat : 1.0~a1-0dlb1
 Table de version :
 *** 1.0~a1-0dlb1 0
        500 https://packages.temboard.io/apt/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status
```

Tell me if you need more details.

Thanks.

**Comment by bersace** [comment]
Hi,

Ok, thanks for pointing the source of the installation (.deb here). Actually, the .deb package available is alpha. The PR is'nt even merge.

@julmon we must allow multiple versions of the package in our repository. Uploading 1.0~a1 **dropped** `0.0.1` previous package !

See bugs.debian.org/cgi-bin/bugreport.cgi?bug=570623

**Comment by bersace** [comment]
@julmon should we upload alpha only in `sid` ? Or provide an `expiremental` repository ?

**Comment by bersace** [comment]
Anyway, we should not upload alpha release on .deb.

**Comment by julmon** [comment]
We're just trying release process with this alpha.

**Comment by bersace** [comment]
aptly does the trick to publish several versions of a package in the same repo. https://www.aptly.info/

**Comment by bersace** [comment]
Ok, fixed : temboard-agent available at http://apt.dalibo.org/ is ok and `apt.dalibo.org` supports multiple versions of packages \o/

**Comment by julmon** [comment]
KUDOS @bersace ! \o/

**Comment by aanriot** [comment]
Great @bersace!

Could you tell me how I can fetch the GPG key of the repository? The command mentionned at [apt.dalibo.org](http://apt.dalibo.org/) seems to be wrong.

By the way, it's probably under control but the instructions at [readthedocs.io](https://temboard.readthedocs.io/en/latest/temboard-agent-install-debian/) are still mentionning the old repository.

Thanks.

**Comment by bersace** [comment]
@aanriot http://apt.dalibo.org/ Merci !!
