### ISSUE TITLE
Invalid temboard_port from config

### ISSUE THREAD

**Issue by xroman70** [dalibo/temboard-agent#480]
Failed to start agent with error:
systemd[1]: Started PostgreSQL Remote Control Agent 11/pg5432.
 env[26122]: INFO: Starting temboard-agent 6.0.
 env[26122]: ERROR: Invalid temboard_port from config: invalid literal for int() with base 10: ''...
 env[26122]: CRITI: Failed to load configuration.
 systemd[1]: temboard-agent@11-pg5432.service: main process exited, code=exited, status=1/FAILURE
 systemd[1]: Unit temboard-agent@11-pg5432.service entered failed state.
 systemd[1]: temboard-agent@11-pg5432.service failed

Any help would be appreciated.

**Comment by pgiraud** [comment]
Can you also please check what's the port set in `/etc/temboard-agent/11/temboard-agent.conf.d/auto.conf`?

**Comment by pgiraud** [comment]
ping @xroman70

**Comment by xroman70** [comment]
/etc/temboard-agent/11/pg5432/temboard-agent.conf.d/auto.conf

[temboard]
home = /var/lib/temboard-agent/11/pg5432
hostname = dev-gt-db-01.prv.gen.io
port = 2345                                                                                      < port was missing 
ssl_cert_file = /etc/pki/tls/certs/temboard-agent-11-pg5432.pem
ssl_key_file = /etc/pki/tls/private/temboard-agent-11-pg5432.key
key = 9893a381c7ac6348fb6da555af695b6f

**Comment by xroman70** [comment]
Getting different error for the agent status:
systemd[1]: Started PostgreSQL Remote Control Agent 11/pg5432.
 env[18591]: INFO: Starting temboard-agent 7.1.
 env[18591]: ERROR: Invalid postgresql_host from config: Not a directory...
 env[18591]: CRITI: Failed to load configuration.
 systemd[1]: temboard-agent@11-pg5432.service: main process exited, code=exited, status=1/FAILURE
 systemd[1]: Unit temboard-agent@11-pg5432.service entered failed state.
 systemd[1]: temboard-agent@11-pg5432.service failed.

**Comment by pgiraud** [comment]
@xroman70 Can you also please check what's the value for `host` in the `postgresql` section both in auto.conf and temboard-agent.conf?

**Comment by xroman70** [comment]
In /etc/temboard-agent/11/temboard-agent.conf 

[postgresql]
# Unix socket path.
host = dev-gt-db-01.prv.gen.io

In /etc/temboard-agent/11/pg5432/temboard-agent.conf.d/auto.conf

[postgresql]
host = dev-gt-db-01.prv.gen.io

**Comment by xroman70** [comment]
[root@dev-gt-db-01 temboard-agent]# find /etc/temboard-agent/ -name  "*conf"
/etc/temboard-agent/11/pg5432/temboard-agent.conf.d/auto.conf
/etc/temboard-agent/11/pg5432/temboard-agent.conf
/etc/temboard-agent/11/temboard-agent.conf
/etc/temboard-agent/temboard-agent.conf

**Comment by xroman70** [comment]
Values for host/hostname from above listed files :

[root@dev-gt-db-01 temboard-agent]# find /etc/temboard-agent/ -name  "*conf" -exec grep 'host' {} \;
hostname = dev-gt-db-01.prv.gen.io
host = dev-gt-db-01.prv.gen.io
# If you leave this empty, then the system wide hostname will be used
# Note : `localhost` is not a correct value
# hostname = db1.mydomain.foo
host = dev-gt-db-01.prv.gen.io
# DB name hosting pg_stat_statements view (the one where the extension has
# If you leave this empty, then the system wide hostname will be used
# Note : `localhost` is not a correct value
hostname = dev-gt-db-01.prv.gen.io
host = dev-gt-db-01.prv.gen.io
# If you leave this empty, then the system wide hostname will be used
# Note : `localhost` is not a correct value
# hostname = db1.mydomain.foo
host = dev-gt-db-01.prv.gen.io

**Comment by pgiraud** [comment]
The value for `host` in the `postgresql` section should actually be the path to the UNIX socket where postgresql runs.
For example, on a standard installation on CentOS7, it is set to 
```
# Unix socket path.
host = /var/run/postgresql
```

**Comment by xroman70** [comment]
The agent has been started:
 systemctl status temboard-agent@11-pg5432
● temboard-agent@11-pg5432.service - PostgreSQL Remote Control Agent 11/pg5432
   Loaded: loaded (/usr/lib/systemd/system/temboard-agent@.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2020-10-09 14:45:05 UTC; 16s ago
 Main PID: 1960 (temboard-agent)
   CGroup: /system.slice/system-temboard\x2dagent.slice/temboard-agent@11-pg5432.service
           ├─1960 temboard-agent: 11/pg5432: main process
           ├─1965 temboard-agent: 11/pg5432: worker pool
           ├─1966 temboard-agent: 11/pg5432: scheduler
           └─1970 temboard-agent: 11/pg5432: worker pool

**Comment by pgiraud** [comment]
That's good news! Thanks. Closing.
