### ISSUE TITLE
Which temboard-agent.conf File is Being Used?

### ISSUE THREAD

**Issue by bsislow** [dalibo/temboard-agent#487]
FYI, we're on version 7 agent:
```
[root@dbpg02 temboard-agent.conf.d]# rpm -qa | grep temboard
temboard-agent-7.0a6-1.el7.noarch
```

what `temboard-agent.conf` is actually being used? we are confused.

I see the following; we used auto configure to set this instance up:
```
# find . -name 'temboard-agent.conf'
./12/pg45221/temboard-agent.conf
./temboard-agent.conf
```

also, i see the `auto.conf` under `/etc/temboard-agent/12/pg45221/temboard-agent.conf.d`. i assume this overrides any values in the active `temboard-agent.conf`?

finally, what is the recommended method to "merge" values that are new or modified in the `temboard-agent.conf.rpmnew` file into our existing `temboard-agent.conf` file?

thanks.

**Comment by bersace** [comment]
There is multiple ways to start agent in rpm base systems :

- systemctl start temboard-agent@12-pg45221 is the modern way, allowing multiple agent on single host
- systemctl start temboard-agent is the previous way
- We still ship /etc/init.d/temboard-agent for very old systems.

Ho do you start agent ? 

systemctl status should give you more details, can you share systemctl status temboard-agent... ?

**Comment by bsislow** [comment]
here's an example.... i don't see anything about which conf file is used here:

```
● temboard-agent@12-pg45221.service - PostgreSQL Remote Control Agent 12/pg45221
   Loaded: loaded (/usr/lib/systemd/system/temboard-agent@.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2020-10-12 19:50:31 CDT; 1 day 12h ago
 Main PID: 42596 (temboard-agent)
   CGroup: /system.slice/system-temboard\x2dagent.slice/temboard-agent@12-pg45221.service
           ├─33829 temboard-agent: 12/pg45221: worker pool
           ├─42596 temboard-agent: 12/pg45221: main process
           ├─42609 temboard-agent: 12/pg45221: worker pool
           └─42610 temboard-agent: 12/pg45221: scheduler

Oct 14 08:09:16 pgsdsm004p.prd.chi.accertify.net env[42596]: Loaded probe: temp_files_size_delta
Oct 14 08:09:16 pgsdsm004p.prd.chi.accertify.net env[42596]: Loaded probe: sessions
Oct 14 08:09:16 pgsdsm004p.prd.chi.accertify.net env[42596]: Loaded probe: xacts
Oct 14 08:09:16 pgsdsm004p.prd.chi.accertify.net env[42596]: Loaded probe: btree_bloat
Oct 14 08:09:16 pgsdsm004p.prd.chi.accertify.net env[42596]: Loaded probe: memory
Oct 14 08:09:16 pgsdsm004p.prd.chi.accertify.net env[42596]: Loaded probe: heap_bloat
Oct 14 08:09:16 pgsdsm004p.prd.chi.accertify.net env[42596]: Loaded probe: loadavg
Oct 14 08:09:16 pgsdsm004p.prd.chi.accertify.net env[42596]: Loaded probe: filesystems_size
Oct 14 08:09:16 pgsdsm004p.prd.chi.accertify.net env[42596]: Loaded probe: cpu
Oct 14 08:09:16 pgsdsm004p.prd.chi.accertify.net env[42596]: Loaded probe: bgwriter
```

**Comment by bersace** [comment]
Hi @bsislow . The configuration is un `/etc/temboard-agent/12/pg45221/temboard-agent.conf` **and** `/etc/temboard-agent/12/pg45221/temboard-agent.conf.d`.

**Comment by bsislow** [comment]
thanks... we will use those under the corresponding instance moving forward.
