### ISSUE TITLE
All temboard-agents Which Do Not Use auto_configure.sh Script Broken After Upgrading to v7

### ISSUE THREAD

**Issue by bsislow** [dalibo/temboard-agent#488]
all agents where we did not use the "auto_configure.sh" method (older deployments) are now broken with this:

![image](https://user-images.githubusercontent.com/30243584/95791370-db670b80-0ca6-11eb-8cfb-d4057ea52c43.png)

our simple fix is to remove and re-deploy the agent, but just thought you should know this is going on.

**Comment by bersace** [comment]
Hi @bsislow thanks for reaching. Do you have temboard UI log message when accessing an old agent installation ?

**Comment by bsislow** [comment]
will try to provide soon; we're upgrading temboard in a different data center this coming week.

**Comment by bersace** [comment]
@bsislow Thanks. Anything about agent installation is wellcome too : version, configuration, logs, init script, etc.

**Comment by bsislow** [comment]
we continued the upgrade in the different data center and when we upgrade the agent itself to 7 from 6 (UI is already at 7), we get the same error again. i had to go through all of the agent in the other data center and re-deploy them (painful) - so i'd like to figure this out instead of doing that again. we're leaving one agent at v7 and the others at 6 (so they function) so i can collect data for you as needed.

what you've requested so far:

```
# rpm -qa | grep temboard
temboard-agent-7.0a6-1.el7.noarch
temboard-7.2-1.el7.noarch
```

can i send the rest of the information to an email address for privacy? i can send you full logs for your analysis.

thanks.

**Comment by bsislow** [comment]
any update on this? we're still waiting to upgrade based on the output of this bug.

**Comment by pgiraud** [comment]
Unfortunately we didn't have time to work on this issue. I'm very sorry for that.

**Comment by pgiraud** [comment]
@bsislow Can you please send me information as asked by @bersace in October? https://github.com/dalibo/temboard-agent/issues/488#issuecomment-709842979
I think you already have my email address. But just in case, it is pierre (dot) giraud (at) dalibo (dot) com.
If you have already sent information to @bersace please forward it to me. He is unfortunately on sick leave right now.

**Comment by bsislow** [comment]
i believe what's happening here is the software, when following the upgrade steps here:
https://temboard.readthedocs.io/projects/agent/en/v7/upgrade.html#x-to-7-0
... is not considering any non-default configurations.

for example, we do not install postgres on port 5432; we use a non-standard port.

we see the following service before we upgrade to 7:
```
# systemctl -a | grep temboard
  temboard-agent@12-pg45221.service                                                                              loaded    active   running   PostgreSQL Remote Control Agent 12/pg45221
```

after upgrading, we see:
```
# systemctl -a | grep temboard
  temboard-agent.service                                                                                                                   loaded    active   running   temBoard agent for PostgreSQL
```

it appears the upgrade wipes out the auto-configured agent and replaces it with a default one.

here's what we see in the agent log after upgrading (which also changes in name from /var/log/temboard-agent/12-pg45221.log to temboard-agent.log):
```
2020-12-11 22:08:48,377 temboardagent[8881]: [root] ERROR: Failed to connect to Postgres: could not connect to server: No such file or directory
2020-12-11 22:08:48,377 temboardagent[8881]: [root] ERROR:      Is the server running locally and accepting
2020-12-11 22:08:48,377 temboardagent[8881]: [root] ERROR:      connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
2020-12-11 22:08:48,377 temboardagent[8881]: [root] ERROR: Traceback (most recent call last):
2020-12-11 22:08:48,377 temboardagent[8881]: [root] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/plugins/monitoring/inventory.py", line 55, in instance_info
2020-12-11 22:08:48,377 temboardagent[8881]: [root] ERROR:     with Postgres(**conninfo).connect() as conn:
2020-12-11 22:08:48,377 temboardagent[8881]: [root] ERROR:   File "/usr/lib/python2.7/site-packages/temboardagent/postgres.py", line 73, in __enter__
2020-12-11 22:08:48,377 temboardagent[8881]: [root] ERROR:     raise UserError("Failed to connect to Postgres: %s" % e.message)
2020-12-11 22:08:48,377 temboardagent[8881]: [root] ERROR: UserError: Failed to connect to Postgres: could not connect to server: No such file or directory
2020-12-11 22:08:48,377 temboardagent[8881]: [root] ERROR:      Is the server running locally and accepting
2020-12-11 22:08:48,377 temboardagent[8881]: [root] ERROR:      connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
2020-12-11 22:08:48,377 temboardagent[8881]: [root] WARNING: Unable to gather information for cluster "main"
```

**Comment by pgiraud** [comment]
> it appears the upgrade wipes out the auto-configured agent and replaces it with a default one.

What I don't understand is that you were talking about agents that were not configured with `auto_configure`. Are you sure you didn't run the `auto_configure.sh` script on this agent?

Can you please show the content of the different config files?
`/etc/temboard-agent/12/data/temboard-agent.conf`
`/etc/temboard-agent/12/data/temboard-agent.conf.d/auto.conf`

The paths may be a bit different on your server.

As far as I know, there is no reason why the configuration should be changed if you follow the upgrade instructions.

**Comment by pgiraud** [comment]
@bsislow I think I have an other explanation to your problems. The documentation telling how to upgrade temboard agent is asking you to stop the agent, update the package, then do some other stuff, and finally start the agent.
Some commands are given but they have to be used carefully. What we unfortunately forgot to mention is that you have to adapt those commands to your own environnement.
In your case the service seem to be 'temboard-agent@12-pg45221'. This means that you would have to stop/start the service using the following command:
```
sudo systemctl stop temboard-agent@12-pg45221
sudo systemctl start temboard-agent@12-pg45221
```
Starting `temboard-agent` is wrong since it will start a service with a default config, not the one you want it to use.

**Comment by bsislow** [comment]
We started the old services successfully; no concerns. Somehow we missed this. Thanks.
