### ISSUE TITLE
temboard-agent 7.3 - since update plugin status doesn't work

### ISSUE THREAD

**Issue by vidierr** [dalibo/temboard-agent#502]
Hello,

I have updated an agent from 7.2 to 7.3 et installed an agent 7.3 on another server and the "status" page on all the agent 7.3 doesn't work anymore.

Temboard 7.3, agent 7.3 doesn't work, agent 7.2 work, on RHEL 7 and 8

The errors in /var/log/messages :
"Nov 16 17:20:06 server1 env: client: x.x.x.x request: "GET /profile?key=xxxxxxxxxxxxxxxxxxxxxx HTTP/1.1" 401 - 2.35ms
Nov 16 17:20:20 server1 env: Loaded probe: sessions
Nov 16 17:20:20 server1 env: Loaded probe: xacts
Nov 16 17:20:20 server1 env: Loaded probe: locks
Nov 16 17:20:20 server1 env: Loaded probe: blocks
Nov 16 17:20:20 server1 env: Loaded probe: bgwriter
Nov 16 17:20:20 server1 env: Loaded probe: db_size
Nov 16 17:20:20 server1 env: Loaded probe: tblspc_size
Nov 16 17:20:20 server1 env: Loaded probe: filesystems_size
Nov 16 17:20:20 server1 env: Loaded probe: cpu
Nov 16 17:20:20 server1 env: Loaded probe: process
Nov 16 17:20:20 server1 env: Loaded probe: memory
Nov 16 17:20:20 server1 env: Loaded probe: loadavg
Nov 16 17:20:20 server1 env: Loaded probe: wal_files
Nov 16 17:20:20 server1 env: Loaded probe: replication_lag
Nov 16 17:20:20 server1 env: Loaded probe: temp_files_size_delta
Nov 16 17:20:20 server1 env: Loaded probe: replication_connection
Nov 16 17:20:20 server1 env: Loaded probe: heap_bloat
Nov 16 17:20:20 server1 env: Loaded probe: btree_bloat
Nov 16 17:20:20 server1 env: <class 'TypeError'>: Object of type 'datetime' is not JSON serializable
Nov 16 17:20:20 server1 env: Traceback (most recent call last):
Nov 16 17:20:20 server1 env:  File "/usr/lib/python3.6/site-packages/temboardagent/toolkit/taskmanager.py", line 882, in exec_worker
Nov 16 17:20:20 server1 env:    res = getattr(sys.modules[module], function)(*args, **kws)
Nov 16 17:20:20 server1 env:  File "/usr/lib/python3.6/site-packages/temboardagent/toolkit/taskmanager.py", line 1046, in wrapper
Nov 16 17:20:20 server1 env:    return function(app=self.app, *a, **kw)
Nov 16 17:20:20 server1 env:  File "/usr/lib/python3.6/site-packages/temboardagent/plugins/monitoring/__init__.py", line 270, in monitoring_collector_worker
Nov 16 17:20:20 server1 env:    output
Nov 16 17:20:20 server1 env:  File "/usr/lib/python3.6/site-packages/temboardagent/plugins/monitoring/db.py", line 49, in add_metric
Nov 16 17:20:20 server1 env:    (time, json.dumps(data))
Nov 16 17:20:20 server1 env:  File "/usr/lib64/python3.6/json/__init__.py", line 231, in dumps
Nov 16 17:20:20 server1 env:    return _default_encoder.encode(obj)
Nov 16 17:20:20 server1 env:  File "/usr/lib64/python3.6/json/encoder.py", line 199, in encode
Nov 16 17:20:20 server1 env:    chunks = self.iterencode(o, _one_shot=True)
Nov 16 17:20:20 server1 env:  File "/usr/lib64/python3.6/json/encoder.py", line 257, in iterencode
Nov 16 17:20:20 server1 env:    return _iterencode(o, 0)
Nov 16 17:20:20 server1 env:  File "/usr/lib64/python3.6/json/encoder.py", line 180, in default
Nov 16 17:20:20 server1 env:    o.__class__.__name__)
Nov 16 17:20:20 server1 env: TypeError: Object of type 'datetime' is not JSON serializable"

Best regards,
Rémi

**Comment by pgiraud** [comment]
@vidierr A new version of temboard-agent has been released. It includes a fix for the issue you faced. Can you please have a try with installing temboard-agent 7.4?
Thanks for the report.

**Comment by vidierr** [comment]
@pgiraud it's work fine whith version 7.4.
Thank you for the quick fix.

**Comment by pgiraud** [comment]
Thanks.
