### ISSUE TITLE
Custom Date Range Issues on Monitoring Screen

### ISSUE THREAD

**Issue by bsislow** [dalibo/temboard-agent#509]
I noticed a few issues with custom date ranges...

First, if you select a start date, the end date is restricted to an arbitrary end date; this doesn't make any sense:

![image](https://user-images.githubusercontent.com/30243584/102145600-23ccb200-3e2d-11eb-8068-77f725d28418.png)

Why can't we select any date/time later than Thu Dec 10 2020 12:00:00 GMT-0600 in this example?

---

Second, when I enter my own seemingly _valid_ date, the field results in "Invalid date." I copied and pasted the date, and added 5 minutes to the time. Unsure what is wrong here...

![image](https://user-images.githubusercontent.com/30243584/102145715-58d90480-3e2d-11eb-9369-22422e70c6ec.png)

**Comment by pgiraud** [comment]
Duplicate for https://github.com/dalibo/temboard/issues/878
Closing
