### ISSUE TITLE
Use exception in configuration file

### ISSUE THREAD

**Issue by Mika313** [dalibo/temboard-agent#516]
Hi all,

In the configuration file, is there a way to set a parameter to all except _value_?
For exemple, i want to run all probes except `cpu`.
I have to list all probes except `cpu`?

Thanks and Regards.

**Comment by pgiraud** [comment]
Unfortunately, this feature doesn't exist yet.

**Comment by Mika313** [comment]
Ok it was just in case of ; )
Thanks and Regards
