### ISSUE TITLE
Temboard-agent error : no more monitoring data available

### ISSUE THREAD

**Issue by ced75** [dalibo/temboard-agent#517]
Hi,

One off my monitored server does no more display monitoring data.
Temboard server and temBoard agent are both in 7.5 version.

On the agent server, I get the following error:

> févr. 09 19:21:09 new-del1207w108 env[1516]: <class 'TypeError'>: datetime.datetime(2021, 2, 9, 19, 21, 9, 150267, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=60, name=None)) is not JSON serializable
févr. 09 19:21:09 new-del1207w108 env[1516]: Traceback (most recent call last):
févr. 09 19:21:09 new-del1207w108 env[1516]:   File "/usr/lib/python3.5/dist-packages/temboardagent/toolkit/taskmanager.py", line 882, in exec_worker
févr. 09 19:21:09 new-del1207w108 env[1516]:   File "/usr/lib/python3.5/dist-packages/temboardagent/toolkit/taskmanager.py", line 1046, in wrapper
févr. 09 19:21:09 new-del1207w108 env[1516]:   File "/usr/lib/python3.5/dist-packages/temboardagent/plugins/monitoring/__init__.py", line 270, in monitoring_collector_worker
févr. 09 19:21:09 new-del1207w108 env[1516]:   File "/usr/lib/python3.5/dist-packages/temboardagent/plugins/monitoring/db.py", line 49, in add_metric
févr. 09 19:21:09 new-del1207w108 env[1516]:   File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
févr. 09 19:21:09 new-del1207w108 env[1516]:     return _default_encoder.encode(obj)
févr. 09 19:21:09 new-del1207w108 env[1516]:   File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
févr. 09 19:21:09 new-del1207w108 env[1516]:     chunks = self.iterencode(o, _one_shot=True)
févr. 09 19:21:09 new-del1207w108 env[1516]:   File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
févr. 09 19:21:09 new-del1207w108 env[1516]:     return _iterencode(o, 0)
févr. 09 19:21:09 new-del1207w108 env[1516]:   File "/usr/lib/python3.5/json/encoder.py", line 179, in default
févr. 09 19:21:09 new-del1207w108 env[1516]:     raise TypeError(repr(o) + " is not JSON serializable")
févr. 09 19:21:09 new-del1207w108 env[1516]: TypeError: datetime.datetime(2021, 2, 9, 19, 21, 9, 150267, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=60, name=None)) is not JSON serializable

Could it be related to Python version on the monitored server?
Thanks in advance for your help,

Cedric

**Comment by dlax** [comment]
Also, I would kindly suggest anyone to move away from using python 3.5: it's not a supported version (for a long time) and it's a significant maintenance burden on our side.

**Comment by ced75** [comment]
Unfortunately, I do not have any `dist_packages` directory in `/usr/lib/python3.5`.
I will ask for a Linux Debian upgrade to buster for this server.
This should at least resolve the Python version problem.

**Comment by dlax** [comment]
The trace you posted initially mentions files in `/usr/lib/python3.5/dist-packages/temboardagent/`. That may come from an "old" (pre 7.4) temboard-agent debian package.

**Comment by ced75** [comment]
Yes, probably, since I regularly upgraded temBoard-agent on this server.

**Comment by dlax** [comment]
What do you mean? Are those files there or not?

**Comment by ced75** [comment]
No, there remains no Python files in python3.5 directory.

**Comment by dlax** [comment]
That's very strange then and I fail to explain why these are mentioned in the trace you posted.

I am closing this issue because there's apparently nothing more we can do.

**Comment by ced75** [comment]
I'm waiting for a Debian upgrade on the server. I wish it would solve the issue.
