### ISSUE TITLE
list of little bug during installation

### ISSUE THREAD

**Issue by egaultier** [dalibo/temboard-agent#532]
Hi 

Below a list of little bug during the installation of Tembaord-agent 7.7 on redhat 7.9

Pg 13.3 on the server

When I execute the **sudo -u postgres temboard-agent-adduser -c /etc/temboard-agent/13/data/temboard-agent.conf**
I Have this error : 

_INFO: Starting temboard-agent-adduser 7.7.
CRITI: [Errno 13] Permission denied: '/etc/temboard-agent/13/data/temboard-agent.conf.d/auto.conf'_

change permission to 644 for auto.conf file.

When I start the temboard-agent service, I have this error :

**systemctl start temboard-agent@13-data.service**

_temboardagent[210045]: [app] CRITICAL: Failed to setup SSL: [Errno 13] Permission denied._

Change permission to 644 for the files :

ssl_cert_file = /etc/pki/tls/certs/temboard-agent-xxxxxxxxxxx.pem
ssl_key_file = /etc/pki/tls/private/temboard-agent-xxxxxxxxxxx.key

Emmanuel

**Comment by bersace** [comment]
Hi @egaultier . Thanks for the feedback. What is the output of

``` console
$ namei -om /etc/pki/tls/private/temboard-agent-xxxxxxxxxxx.key
$ namei -om /etc/pki/tls/certs/temboard-agent-xxxxxxxxxxx.pem
$ namei -om /etc/temboard-agent/13/data/temboard-agent.conf.d/auto.conf
```

Merci.

**Comment by egaultier** [comment]
**namei -om /etc/temboard-agent/13/data/temboard-agent.conf.d/auto.conf**

![image](https://user-images.githubusercontent.com/67147948/121027313-276f3f00-c7a7-11eb-9ed1-4199ce3507e4.png)

**namei -om /etc/pki/tls/private/temboard-agent-13-data.key**

![image](https://user-images.githubusercontent.com/67147948/121027245-1b837d00-c7a7-11eb-93fe-4e2e4b780f5e.png)

**namei -om /etc/pki/tls/certs/temboard-agent-13-data.pem**

![image](https://user-images.githubusercontent.com/67147948/121027508-4d94df00-c7a7-11eb-9643-61df6465b612.png)

**Comment by egaultier** [comment]
Hi

I do the same install, Temboard-agent 7.7, on an other Redhat 7.9 server. I Had the same errors.
Same install on CentOs 8.3, I didn't have these errors.

Emmanuel

**Comment by bersace** [comment]
@egaultier Do you have SELinux enabled ?

**Comment by egaultier** [comment]
Hi

SELinux is disabled

Emmanuel

**Comment by bersace** [comment]
@egaultier what is the umask for root ?

**Comment by egaultier** [comment]
Hi 

![image](https://user-images.githubusercontent.com/67147948/143202890-8c98ef6a-1f65-4e35-a4a9-4dfdad408fb3.png)

Emmanuel

**Comment by bersace** [comment]
@egaultier that's it. Thanks !
