### ISSUE TITLE
Impossible to upgrade to temboard-agent 7.8 on Debian Stretch

### ISSUE THREAD

**Issue by ced75** [dalibo/temboard-agent#537]
Hi,

I'm still facing difficulties with temboard upgrades.
On several servers, which are with a Stretch Debian Linux version, the apt-get update and upgrade are no more possible.
Here is what I get for apt-get update:

> Err:10 https://apt.dalibo.org/labs stretch-dalibo Release
>   server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

And when I try to upgrade by installing temboard-agent with apt-get install, I get the following error:

> Les paquets suivants seront mis à jour :
>   temboard-agent
> 1 mis à jour, 0 nouvellement installés, 0 à enlever et 118 non mis à jour.
> Il est nécessaire de prendre 97,7 ko dans les archives.
> Après cette opération, 0 o d'espace disque supplémentaires seront utilisés.
> Err:1 http://apt.dalibo.org/labs stretch-dalibo/main all temboard-agent all 7.8-0dlb1stretch1
>   server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
> Err:1 https://apt.dalibo.org/labs stretch-dalibo/main amd64 temboard-agent all 7.8-0dlb1stretch1
>   server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
> E: Impossible de récupérer http://apt.dalibo.org/labs/pool/main/t/temboard-agent/temboard-agent_7.8-0dlb1stretch1_all.deb  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
> E: Impossible de récupérer certaines archives, peut-être devrez-vous lancer apt-get update ou essayer avec --fix-missing ?
> 

I can't migrate to Buster for the moment. How can I solve this issue?

Thanks in advance for your help,

Cedric

**Comment by bersace** [comment]
Hi,

This looks like a repository issue. You may need to update ca-certificates from debian updates.

**Comment by ced75** [comment]
Hi,
 
Done:
>sudo apt install ca-certificates
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
ca-certificates is already the newest version (20200601~deb9u2).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 138 non mis à jour.

but the problem remains.

**Comment by bersace** [comment]
Salut @ced75 , le dépôt APT est maintenant accessible en HTTP clair, peux-tu retenter ?

**Comment by ced75** [comment]
Bonjour @bersace,

J'ai testé et ça fonctionne de nouveau.
Merci pour la mise à jour.

**Comment by bersace** [comment]
Super !
