### ISSUE TITLE
app=[unknown] in postgres log

### ISSUE THREAD

**Issue by egaultier** [dalibo/temboard-agent#564]
Hi 

A little improvement, all request executing by Temboard-agent are listed in log postgres with app=[unknown].

![image](https://user-images.githubusercontent.com/67147948/154291676-1f385951-89dd-463c-ba37-1332b00b1bcd.png)

It's possible to have app=[temboard-agent]

Thank 

Emmanuel

**Comment by bersace** [comment]
Hi @egaultier this is just implemented in 7.10rc2, final release very soon !

**Comment by egaultier** [comment]
Hi @bersace 

Good news.
I close this issue.

Thank you. Have a nice day.

Emmanuel
