### ISSUE TITLE
Error Invalid Key - After upgrade 7.10

### ISSUE THREAD

**Issue by egaultier** [dalibo/temboard-agent#568]
Hello

After upgrade temboard-agent to 7.10.

In temboard central console, we have invalid key error for the updated client

We have the same message with command : systemctl status temboard-agent

![image](https://user-images.githubusercontent.com/67147948/155487698-2f66576a-42f6-4d6c-b3cc-44e63473d64c.png)

We have the same error for a second updated client.

Thank you for your help

Emmanuel

**Comment by bersace** [comment]
What version of temBoard UI are you using ?

**Comment by egaultier** [comment]
Temboard 7.8

**Comment by bersace** [comment]
Hi @egaultier I can't reproduce. I suggest you to upgade UI to 7.10, iit has better error handling. Also, could you check agent configuration and parameter in temboard UI settings ? Did you update the key ?

**Comment by egaultier** [comment]
Hi

I upgrade my temboard IU to 7.10. 

I always have the same message for updated tembaord-agent to 7.10

After updating a new temboard-agent, I have the same message.

I don't update any key.

Thank you

**Comment by egaultier** [comment]
For test. 

I purge/configure again one of updated temboard-agent.

with purge.sh 
I delete this client on Temboard IU
and auto_configure.sh

After this operation, I have the same error !!!
The secret key have changed with this operation.

Bizarre vous avez dit bizarre !

Emmanuel

**Comment by bersace** [comment]
@egaultier can you send me `DEBUG=y auto_configure.sh` logs, agent logs (DEBUG) and UI logs (DEBUG) ? etienne POINT bersac AD dalibo POINT com

**Comment by egaultier** [comment]
Hi 

Sorry for my late answer.

I will do the requested operations tomorrow 

Emmanuel

**Comment by bersace** [comment]
:up:

**Comment by egaultier** [comment]
Hi

@bersace, I send you the requested logs.

**Comment by egaultier** [comment]
Hi bersace

Thank you for your help now it all for all my updated agent.

Have a nice day.

Emmanuel
