### ISSUE TITLE
Task Manager

### ISSUE THREAD

**Issue by julmon** [dalibo/temboard-agent#70]
# Task Manager

## Why ?

Temboard agent should be able to do stuffs (possibly long) asynchronously without blocking the other processes. The current implementation is not good.

## Needs

Temboard agent needs to:
- Execute asynchronous tasks : vacuuming a table, monitoring data collecting, dashboard data collecting, sending monitoring data, cleaning user sessions etc..
- Cancel a work-in-progress task.
- Schedule a new task on-demand, ex: vacuuming a table.
- Know the task list, with their state: `WIP`, `DONE`, `FAILED` etc..
- Schedule periodical tasks, ex: monitoring data collecting should be done every 60 seconds
- Save on-disk the task list, for the durability. We need to know when was the last time that a periodical task has been done for scheduling its next execution.
- Limit the number of WIP tasks for each kind of worker. ex: we want to limit the number of vacuum to 3 at the same time.
- Not schedule a task that has already been scheduled, ex: vacuum this table of this DB at this time shouldn't be scheduled twice.
- Schedule the execution of a task at a defined time slot.
- Retry to execute a previously failed task `X` time.
- Know the remaining work to do to complete the execution of a task, if possible. ex: vacuum of the table at 50%

**Comment by bersace** [comment]
https://apscheduler.readthedocs.io/en/latest/ is a good candidate to at least borrow concepts and semantic.

**Comment by julmon** [comment]
Done !
